import {
  MdLibraryBooks,
  MdPayment,
  MdVideoCall,
  MdUpdate,
  MdPersonAdd,
} from 'react-icons/md';

export const PRIORITIES = ['critical', 'high', 'medium', 'low'];

export const PRIORITY_META = {
  critical: {
    label: 'Critical',
    iconBg: '#EF4444',
    badgeBg: 'rgba(239, 68, 68, 0.15)',
    badgeBorder: 'rgba(239, 68, 68, 0.35)',
    badgeText: '#FCA5A5',
  },
  high: {
    label: 'High',
    iconBg: '#F97316',
    badgeBg: 'rgba(249, 115, 22, 0.15)',
    badgeBorder: 'rgba(249, 115, 22, 0.35)',
    badgeText: '#FDBA74',
  },
  medium: {
    label: 'Medium',
    iconBg: '#3B82F6',
    badgeBg: 'rgba(59, 130, 246, 0.15)',
    badgeBorder: 'rgba(59, 130, 246, 0.35)',
    badgeText: '#93C5FD',
  },
  low: {
    label: 'Low',
    iconBg: '#10B981',
    badgeBg: 'rgba(16, 185, 129, 0.15)',
    badgeBorder: 'rgba(16, 185, 129, 0.35)',
    badgeText: '#6EE7B7',
  },
};

export const CATEGORY_META = {
  course: {
    label: 'Course',
    filter: 'Course',
    icon: MdLibraryBooks,
    iconBg: '#3B82F6',
  },
  payment: {
    label: 'Payment',
    filter: 'Payment',
    icon: MdPayment,
    iconBg: '#10B981',
  },
  student: {
    label: 'Student',
    filter: 'Student',
    icon: MdPersonAdd,
    iconBg: '#06B6D4',
  },
  system: {
    label: 'System',
    filter: 'System',
    icon: MdUpdate,
    iconBg: '#F97316',
  },
  live: {
    label: 'Live Sessions',
    filter: 'Live Sessions',
    icon: MdVideoCall,
    iconBg: '#8B5CF6',
  },
};

export const PRIMARY_FILTERS = [
  'All',
  'Course',
  'Payment',
  'Student',
  'System',
  'Live Sessions',
  'Priority',
  'Read/Unread',
];

export const TIMELINE_ORDER = ['Today', 'Yesterday', 'This Week', 'Earlier'];

const buildNotif = (overrides) => ({
  read: false,
  pinned: false,
  archived: false,
  responseMinutes: 12,
  timelineGroup: 'Today',
  ...overrides,
});

export const initialNotifications = [
  buildNotif({
    id: 1,
    category: 'course',
    priority: 'high',
    title: 'New Course Published',
    desc: 'React Native Development by Anushka Sharma is now live and open for enrollment.',
    time: '2 min ago',
    pinned: true,
    timelineGroup: 'Today',
  }),
  buildNotif({
    id: 2,
    category: 'payment',
    priority: 'medium',
    title: 'Payment Received',
    desc: '₹12,999 from Rahul Sharma for Full Stack Web Development.',
    time: '8 min ago',
    timelineGroup: 'Today',
  }),
  buildNotif({
    id: 3,
    category: 'live',
    priority: 'critical',
    title: 'Live Class Starting Soon',
    desc: "Virat Kohli's JavaScript Mastery session begins in 30 minutes. 1,240 students registered.",
    time: '22 min ago',
    pinned: true,
    responseMinutes: 4,
    timelineGroup: 'Today',
  }),
  buildNotif({
    id: 4,
    category: 'student',
    priority: 'low',
    title: 'New Student Registered',
    desc: 'Priya Patel enrolled in Python Foundations.',
    time: '45 min ago',
    read: true,
    timelineGroup: 'Today',
  }),
  buildNotif({
    id: 5,
    category: 'system',
    priority: 'high',
    title: 'System Update Scheduled',
    desc: 'Platform maintenance window tonight from 02:00–04:00 IST.',
    time: '1 hr ago',
    timelineGroup: 'Today',
  }),
  buildNotif({
    id: 6,
    category: 'payment',
    priority: 'critical',
    title: 'Refund Request',
    desc: 'Karan Mehta requested a refund for CSS & UI Design (₹4,999). Requires approval within 24h.',
    time: '2 hrs ago',
    read: true,
    responseMinutes: 45,
    timelineGroup: 'Today',
  }),
  buildNotif({
    id: 7,
    category: 'student',
    priority: 'medium',
    title: 'Course Completion Milestone',
    desc: '500th student completed Full Stack Web Development today!',
    time: '3 hrs ago',
    read: true,
    timelineGroup: 'Today',
  }),
  buildNotif({
    id: 8,
    category: 'course',
    priority: 'critical',
    title: 'Course Review Alert',
    desc: 'A 1-star review was submitted for CSS & UI Design. Instructor notified.',
    time: '5 hrs ago',
    read: true,
    timelineGroup: 'Today',
  }),
  buildNotif({
    id: 9,
    category: 'system',
    priority: 'low',
    title: 'Server Performance Optimal',
    desc: 'All services running normally. Uptime: 99.98%.',
    time: '6 hrs ago',
    read: true,
    timelineGroup: 'Today',
  }),
  buildNotif({
    id: 10,
    category: 'payment',
    priority: 'medium',
    title: 'Revenue Milestone Reached',
    desc: 'Platform crossed ₹25 Lakhs total revenue this month.',
    time: '8 hrs ago',
    read: true,
    timelineGroup: 'Yesterday',
  }),
  buildNotif({
    id: 11,
    category: 'live',
    priority: 'low',
    title: 'Recording Available',
    desc: "Sachin Tendulkar's Python session recording is now available for replay.",
    time: 'Yesterday',
    read: true,
    timelineGroup: 'Yesterday',
  }),
  buildNotif({
    id: 12,
    category: 'student',
    priority: 'high',
    title: 'Bulk Enrollment',
    desc: '28 new students joined via corporate partnership with Infosys.',
    time: 'Yesterday',
    read: true,
    timelineGroup: 'Yesterday',
  }),
  buildNotif({
    id: 13,
    category: 'payment',
    priority: 'high',
    title: 'Failed Payment Retry',
    desc: '3 failed payment attempts for MERN Stack — auto-retry scheduled.',
    time: 'Yesterday',
    read: false,
    timelineGroup: 'Yesterday',
  }),
  buildNotif({
    id: 14,
    category: 'course',
    priority: 'medium',
    title: 'Curriculum Update Approved',
    desc: 'Module 4 of DSA with Java has been updated by MS Dhoni.',
    time: '2 days ago',
    read: true,
    timelineGroup: 'This Week',
  }),
  buildNotif({
    id: 15,
    category: 'system',
    priority: 'critical',
    title: 'Security Alert',
    desc: 'Unusual login attempts detected from 2 IP addresses. Review audit log.',
    time: '2 days ago',
    read: false,
    responseMinutes: 8,
    timelineGroup: 'This Week',
  }),
  buildNotif({
    id: 16,
    category: 'live',
    priority: 'high',
    title: 'Session Capacity Warning',
    desc: 'AI Masterclass is at 95% capacity. Consider opening a second slot.',
    time: '3 days ago',
    read: true,
    timelineGroup: 'This Week',
  }),
  buildNotif({
    id: 17,
    category: 'student',
    priority: 'low',
    title: 'Inactive Learner Batch',
    desc: '142 students inactive for 30+ days. Re-engagement campaign suggested.',
    time: '4 days ago',
    read: true,
    archived: true,
    timelineGroup: 'Earlier',
  }),
  buildNotif({
    id: 18,
    category: 'payment',
    priority: 'medium',
    title: 'Payout Processed',
    desc: 'Instructor payouts for March batch completed — ₹8.4L disbursed.',
    time: '5 days ago',
    read: true,
    timelineGroup: 'Earlier',
  }),
  buildNotif({
    id: 19,
    category: 'course',
    priority: 'low',
    title: 'Quiz Submissions Spike',
    desc: 'Python for ML received 320 quiz submissions in the last hour.',
    time: '6 days ago',
    read: true,
    timelineGroup: 'Earlier',
  }),
  buildNotif({
    id: 20,
    category: 'system',
    priority: 'medium',
    title: 'API Rate Limit Notice',
    desc: 'Third-party integration approaching 80% of daily quota.',
    time: '1 week ago',
    read: true,
    timelineGroup: 'Earlier',
  }),
];
